Present.create(present_name:"パソコン", present_score: 5,present_review:"プログラミングが出来るので嬉しかった。")
Present.create(present_name:"フォーク", present_score: 1,present_review:"意味がわからなかった。")
Present.create(present_name:"腕時計", present_score: 3,present_review:"嬉しいけど好きなブランドでなかった。")
Present.create(present_name:"コーヒー豆", present_score: 4,present_review:"よく飲むから嬉しかった。でも誕生日にはちょっと、、、")
Present.create(present_name:"お肉", present_score: 2,present_review:"固くて不味かった。気持ちは嬉しかった。")
Present.create(present_name:"低音調理器具", present_score: 4,present_review:"嬉しいけど使い方わからない。")

User.create(email:"test@sample", password:"password", nickname:"nickname", gender: 0, age: 2)
User.create(email:"first@sample", password:"password1", nickname:"nickname1", gender: 0, age: 3)
User.create(email:"second@sample", password:"password2", nickname:"nickname2", gender: 0, age: 4)
User.create(email:"thred@sample", password:"password3", nickname:"nickname3", gender: 0, age: 5)
User.create(email:"forth@sample", password:"password4", nickname:"nickname4", gender: 0, age: 6)
User.create(email:"fifth@sample", password:"password5", nickname:"nickname5", gender: 0, age: 7)